#!/bin/bash
rec=${1}
zon=${2}
eml=${3}
bar=${4}

for zonN in $(echo ${zon} | tr "," "\n")
do
    zone_id=$(get_zone_identifier ${zonN} ${bar})
    if [[ -z ${zone_id} ]]; then
        echo -e "[Cloudflare DDNS] Zone identifier not found for zone '${zonN}'"
        exit 1
    fi

    record_id=$(get_record_identifier ${rec} ${zonN} ${bar} ${zone_id})
    if [[ -z ${record_id} ]]; then
        response=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/${zone_id}/dns_records" -H "Authorization: Bearer ${bar}" -H "Content-Type: application/json" --data "{\"type\":\"CNAME\",\"name\":\"${rec}\",\"content\":\"${zonN}\",\"proxied\":true}" )
        if [[ ${response} == *"\"success\":false"* ]]; then
            echo -e "[Cloudflare DDNS] Add DNS record '${rec}' for '${zonN}' failed. DUMPING RESULTS:\n${response}"
            exit 1
        else
            echo -e "[Cloudflare DDNS] Add DNS record ${rec} for '${zonN}' complete. DUMPING RESULTS:\n${response}"
        fi
    else
        echo -e "[Cloudflare DDNS] Add DNS record ${rec} for '${zonN}' already exists."
    fi
done


