#!/usr/bin/env bash
declare -a v1=(0 0 0 0)
declare -a v2=(0 0 0 0)

IFS='.' read -ra var1 <<< "$1"
IFS='.' read -ra var2 <<< "$2"

let comp=0

for i in "${!var1[@]}";do t=${var1[$i]};v1[$i]="${t//[!0-9]/}";done
for i in "${!var2[@]}";do t=${var2[$i]};v2[$i]="${t//[!0-9]/}";done

for i in {0..3}
do
    if [ ${v1[$i]} -lt ${v2[$i]} ]
    then
        comp=1
        break
    elif [ ${v1[$i]} -gt ${v2[$i]} ]
    then
        comp=-1
        break
    fi
done
echo $comp
