#!/bin/bash

zone_id=$(get_zone_identifier ${1} ${2} ${3} ${4})
if [[ -z ${zone_id} ]]; then
    echo -e "[Cloudflare DDNS] Zone identifier not found for zone '${1}'"
    exit 1
fi

record_id=$(get_record_identifier ${1} ${2} ${3} ${4} ${zone_id})
if [[ -z ${record_id} ]]; then
    echo -e "Record '${1}' not exists"
else
    response=$(curl -s -X DELETE "https://api.cloudflare.com/client/v4/zones/${zone_id}/dns_records/${record_id}" -H "X-Auth-Email: ${3}" -H "X-Auth-Key: ${4}" -H "Content-Type: application/json")
    if [[ ${response} == *"\"success\":false"* ]]; then
      echo -e "[Cloudflare DDNS] Delete DNS record ${1} for ${2} failed. DUMPING RESULTS:\n${response}"
      exit 1
    else
      echo -e "[Cloudflare DDNS] Delete DNS record ${1} for ${2} complete. DUMPING RESULTS:\n${response}"
    fi
fi



