#!/bin/bash
rec=${1}
zon=${2}
eml=${3}
bar=${4}

for zonN in $(echo ${zon} | tr "," "\n")
do
    zone_id=$(get_zone_identifier ${zonN} ${bar})
    if [[ -z ${zone_id} ]]; then
        echo -e "[Cloudflare DDNS] Zone identifier not found for zone '${zonN}'"
        exit 1
    fi

    record_id=$(get_record_identifier ${rec} ${zonN} ${bar} ${zone_id})
    if [[ -z ${record_id} ]]; then
        echo -e "Record '${rec}' not exists"
    else
        response=$(curl -s -X DELETE "https://api.cloudflare.com/client/v4/zones/${zone_id}/dns_records/${record_id}" -H "Authorization: Bearer ${bar}" -H "Content-Type: application/json")
        if [[ ${response} == *"\"success\":false"* ]]; then
          echo -e "[Cloudflare DDNS] Delete DNS record ${rec} for ${zonN} failed. DUMPING RESULTS:\n${response}"
          exit 1
        else
          echo -e "[Cloudflare DDNS] Delete DNS record ${rec} for ${zonN} complete. DUMPING RESULTS:\n${response}"
        fi
    fi
done


