#!/bin/bash
rec=${1}
zon=${2}
bar=${3}
zon_id=${4}

response=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${zon_id}/dns_records?name=${rec}.${zon}&type=CNAME" -H "Authorization: Bearer ${bar}" -H "Content-Type: application/json")

if [[ ${response} == *"\"success\":false"* ]]; then
  echo -e "[Cloudflare DDNS] Request record identifier 'https://api.cloudflare.com/client/v4/zones/${zon_id}/dns_records?name=${rec}.${zon}&type=CNAME'"
  echo -e "[Cloudflare DDNS] Get record identifier for '${rec}' in zone ${zon} failed. DUMPING RESULTS:\n${response}"
  exit 1
fi

identifier=$(echo ${response} | sed 's/,/\n/g' | awk -F'"' '/id/{print $6}' | head -1)
if [[ -z ${identifier} ]]; then
  echo ""
else
  echo "${identifier}"
fi



