#!/bin/bash
zon=${1}
bar=${2}

response=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=${zon}" -H "Authorization: Bearer ${bar}" -H "Content-Type: application/json")
if [[ ${response} == *"\"success\":false"* ]]; then
  echo -e "[Cloudflare DDNS] Request zone identifier 'https://api.cloudflare.com/client/v4/zones?name=${zon}'"
  echo -e "[Cloudflare DDNS] Get identifier for zone '${zon}' failed. DUMPING RESULTS:\n${response}"
  exit 1
fi

identifier=$(echo ${response} | sed 's/,/\n/g' | awk -F'"' '/id/{print $6}' | head -1)
if [[ -z ${identifier} ]]; then
  echo ""
else
  echo "${identifier}"
fi



