#!/bin/bash
zon=${1}
eml=${2}
bar=${3}

for zonN in $(echo ${zon} | tr "," "\n")
do
    zone_id=$(get_zone_identifier ${zonN} ${bar})
    if [[ -z ${zone_id} ]]; then
        echo -e "[Cloudflare DDNS] Zone identifier not found for zone '${zonN}'"
    else
        response=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/${zone_id}/purge_cache" -H "Authorization: Bearer ${bar}" -H "Content-Type: application/json" --data "{\"purge_everything\":true}" )
        if [[ ${response} == *"\"success\":false"* ]]; then
            echo -e "[Cloudflare DDNS] Cache purge failed for zone ${zonN}. DUMPING RESULTS:\n${response}\n"
        else
            echo -e "[Cloudflare DDNS] Cache purge done for zone ${zonN}."
        fi
    fi
done



