#!/bin/bash
set -eo pipefail

if [[ "$#" -eq 0 || "${1}" == '-h' || "${1}" == '--help' ]]
then
  cat >&2 <<"EOF"
USAGE:
registry_cleanup_untagged <registry_uri>

EXAMPLE:
registry_cleanup_untagged gcr.io/project-id/hello-folder
EOF
  echo ${1}
  exit 0
fi

deleted=0
registry_uri=${1}

for digest in $(gcloud container images list-tags ${registry_uri} --sort-by=TIMESTAMP --filter="-tags:*" --format='get(digest)');
do
  let deleted+=1
  (
    set -x
    gcloud container images delete --quiet --force-delete-tags "${registry_uri}@${digest}"
  )
done

echo "Deleted ${deleted} images in ${registry_uri}"



